name: Nightly Drift Prototype
on:
  schedule:
    - cron: "17 2 * * *"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  drift:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Prepare directory
        run: |
          mkdir -p metrics
      - name: Generate drift placeholder
        run: |
          echo '{"status":"pending","ts":"'"$(date -u)"'"}' > metrics/nightly_drift.json
      - name: Commit
        run: |
          git config user.name "nebula-bot"
          git config user.email "actions@github.com"
          git add metrics/nightly_drift.json || true
          git commit -m "CHORE: nightly drift placeholder" || echo "No changes"
          git push || true 